### PR TITLE
darwin: Fix build

### PR DESCRIPTION
**Pull request by kirelagin**
Part of #13.

This fixes the build on macOS (and, hopefully, does not break it on Linux).

The thing is still extremely far from being usable on macOS, as it relies on the `linux-ptrace` package, which (as its name implies :) is very Linux specific.

---
This change is [Reviewable](https://reviewable.io/reviews/nh2/hatrace/23)

### CODE REVIEW

**Comment by kirelagin** [comment]
(I should probably add that I actually did not test this change on Linux and, in particular, I am not sure that the CPP thing actually works as expected and adds SIGPOLL to the map on Linux.)

**Comment by qrilka** [comment]
@kirelagin I didn't look into the code but your branch looks ok on Linux, on my desktop Gentoo `stack test` finishing with
```
27 examples, 0 failures, 4 pending                                                                                                      
hatrace-0.1.0.0: Test suite hatrace-test passed
Completed 2 action(s).
```

**Comment by nh2** [comment]
I can confirm this fixes the compilation on Darwin. `InvalidArgment` in the tests, need to do that next :)

**Comment by kirelagin** [comment]
The problem is that `linux-ptrace` uses Linux-specific `ptrace` functionality and it makes calls with magic constants, rather than by including an OS header file, so it doesn’t fail to compile on other platforms, when it actually should. I am not even sure that all required functionality is supported on darwin, although I haven’t looked at what calls it makes and why in detail yet. My feeling is that the next step is creating `darwin-ptrace` and making it API-compatible.

**Comment by nh2** [comment]
Perhaps we should also just make our own ptrace module as part of hatrace, build that from scratch via header file constants, and when we're done and it works well, we can offer it back up to `linux-ptrace`.

**Pull request merged**
