### PR TITLE
Add installation instructions to README

### PR DESCRIPTION
**Pull request by Grazfather**
I am adding this because I know the basics of haskell, playing around in ghci, but struggled to get this installed. I figure adding this will help out people who are intimidated by the probably-new haskell/hackage/cabal ecosystem.

---
This change is [Reviewable](https://reviewable.io/reviews/nh2/hatrace/85)

### CODE REVIEW

**Comment by Grazfather** [comment]
So actually these instructions didn't work for me on both linux and osx.

stack install also didn't work. I can file an issue for this, but if you want to add installation instructions I am happy to change this to correct it.

**Comment by qrilka** [comment]
@Grazfather I suppose we could discuss install problems as a part of this ticket, no special benefit of opening another one and installation instructions are useful I think. `stack install` works fine at least on my machine, what problems do you see on your side?

**Comment by Grazfather** [comment]
Hi qrilka.

I had a bunch, a few fixed up.

1. Cabal was complaining about the comment in _cabal.project_
2. Stack was complaining about the `extra-deps` key being unexpected.
```$ stack install
Could not parse '/home/g/code/hatrace/stack.yaml':
Aeson exception:
Error in $['extra-deps'][0]: failed to parse field 'extra-deps': expected PackageIdentifier, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/
$ stack --version
Version 1.5.1 x86_64
```
3. Both cabal and stack wouldn't 'respect' the forked `posix-waitpid` dep, and so it thought my `base` package was too new.
  * I got around this by uninstalling all my GHC and cabal and reinstalling.
4. _sysinfo.h_ not existing on OSX (is there a `brew` package or something that provides these headers, or the darwin equivalent? I've see the OSX tickets but they don't mention this issue.
5. Building with `runhaskell Setup build` complained about mismatched `#ifdef` with `#endif`

**Comment by nh2** [comment]
Hey @Grazfather, thanks for your fixes! I've just pushed another commit with small refinements into this PR.

For your questions:

> Cabal was complaining about the comment in _cabal.project_

My bad. I've pushed a fix. I copied the comment from `stack.yaml` and forgot that `cabal.project` files, like `.cabal` files, use `--` as comment.

> Stack was complaining about the `extra-deps` key being unexpected.

Your Stack version `1.5.1` is certainly too old. Please get Stack >= 2, which can parse `extra-deps` correctly.

> Both cabal and stack wouldn't 'respect' the forked `posix-waitpid` dep, and so it thought my `base` package was too new.

For Cabal I cannot tell, but for Stack: That should not happen. If I declare my own dependency in `extra-deps`, Stack will either use it, or fail loudly.

The bigger question is though: How did you even get as far as it being ignored, if your Stack already failed at parsing `stack.yaml`?

> _sysinfo.h_ not existing on OSX

This one is better for a separate ticket. Also ask @kirelagin there because I think he knows more about OSX than us.

> Building with `runhaskell Setup build` complained about mismatched `#ifdef` with `#endif`

In which file, can you tell the exact error?

Thanks!

**Comment by Grazfather** [comment]
>The bigger question is though: How did you even get as far as it being ignored, if your Stack already failed at parsing stack.yaml?

I was trying on ubuntu and osx 😅 

```bash
[root@gpwn:~/code/hatrace]$ cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library
[root@gpwn:~/code/hatrace]$ cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library
```

Now I don't think that mismatched `if`/`endif`s is really the issue

```
[root@gpwn:~/code/hatrace]$ cat ./src/System/Hatrace/Types.hsc | grep '#if' | wc -l
87
[root@gpwn:~/code/hatrace]$ cat ./src/System/Hatrace/Types.hsc | grep '#endif' | wc -l
87
```

**Comment by Grazfather** [comment]
I actually got it building on linux, I just had to ditch anything from apt and use ghcup + `cabal install`.

All these versions mixed and matched were hell, but I think that that's just the haskell ecosystem, unfortunately. Might be worth adding a note to the readme about minimum versions for cabal, ghc, etc.

Thank you for the help!

**Comment by nh2** [comment]
> All these versions mixed and matched were hell, but I think that that's just the haskell ecosystem, unfortunately.

@Grazfather If you use the current version of `stack` on Ubuntu, `stack build` should just work out of the box, everything else is a bug.

Could you check that is the case?

**Comment by Grazfather** [comment]
I use both ubuntu 16.04 and 18.04

16.04's `haskell-stack` is 0.1.10.0 and 18.04's is 1.5.1, and both complains about the `extra-deps` part of the config.

**Comment by nh2** [comment]
> 16.04's `haskell-stack` is 0.1.10.0 and 18.04's is 1.5.1, and both complains about the `extra-deps` part of the config.

@Grazfather Yes, I those cannot work, because they are too old for the features we use. My question was to try with the _current version_ of stack, from [haskellstack.org](https://haskellstack.org).

**Comment by Grazfather** [comment]
My mistake, by latest I thought you meant latest available from apt.

I used `curl -sSL https://get.haskellstack.org/ | sh` on a fresh Ubuntu 18.04 and `stack build` worked great.

**Comment by Grazfather** [comment]
Looks like this fell by the wayside. Does this need anything to get merged?

**Comment by nh2** [comment]
> I used `curl -sSL https://get.haskellstack.org/ | sh` on a fresh Ubuntu 18.04 and `stack build` worked great.

Great!

> Does this need anything to get merged?

No, just wanted to check that it works! Thanks!

**Comment by Grazfather** [comment]
Cool, thanks for the merge and for helping me figure out the haskell ecosystem :)

**Pull request merged**
