### PR TITLE
Don't fail when seeing bad pointers in syscall enters or exits

### LINKED ISSUE #73: Don't die on failing peekBytes
(From README) Don't die on `peekBytes` returning `EIO` when the tracee passes invalid memory to the kernel; instead, peek only what's possible and print some info. That makes it possible to correctly trace processes that rely on e.g. `SIGSEGV` handlers.

### PR DESCRIPTION
**Pull request by qrilka**
Resolves #73

---
This change is [Reviewable](https://reviewable.io/reviews/nh2/hatrace/76)

### CODE REVIEW

**Review by nh2 — CHANGES_REQUESTED** [review]
This looks good, I made a few small requests on commentary.

In the future I think it would be nice to observe invalid accesses in more detail over the API, e.g. to be able to write the `let testProgram = "example-programs-build/bad-read-pointer"` test such that you can assert that it does exactly 1 bad `read()` syscall.
Then people could use hatrace to test their programs like "this program shouldn't try to make any syscalls working on invalid data, and if it does, tell me which ones and what they do".

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nh2/hatrace/76#-:-MCMP3OY9MB1vQPbwJzW:b-8i5476)* status: all files reviewed, 5 unresolved discussions (waiting on @qrilka)

___
*[example-programs/bad-read-pointer.c, line 26 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMLn_d5jAz25vEtVhi:-MCMLn_d5jAz25vEtVhj:b-l7gej9) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/example-programs/bad-read-pointer.c#L26)):*
> ```C
>   void* ptr = (void*)42;
>   int res = read(fd, ptr, 1);
>   if (res == -1) {
> ```

Should we also check the `errno` here? Would it be `EFAULT` in this case?
___
*[src/System/Hatrace.hs, line 2113 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMM4177LkA7GTQfmbg:-MCMM4177LkA7GTQfmbh:bh8kbqr) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L2113)):*
> ```Haskell
>   | DetailedSyscallExit_dup2 SyscallExitDetails_dup2
>   | DetailedSyscallExit_dup3 SyscallExitDetails_dup3
>   | DetailedSyscallExit_raw Syscall
> ```

Probably needs a haddock on why we have this.
Same for `RawEnter/ExitDetails` below.

Probably best would be to add a comment section like in GHC's note system:

```
-- Note: [Unpeekable syscalls]
--
-- We cannot obtain/print syscall details in all cases, for example when a bad pointer
-- is given to read()/write(). Instead, we just want to print/return ...
-- We implment this by ... *Raw, ... catching EIO ("HardwareFault") ...
```

and then you can put `-- See note [Unpeekable syscalls]` on the various places relevant to it.
___
*[src/System/Hatrace.hs, line 2145 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMMJ_g5LwUrtINt0Nn:-MCMMJ_g5LwUrtINt0No:bvxv7nh) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L2145)):*
> ```Haskell
>   (syscall, syscallArgs) <- getEnteredSyscall pid
>   let handleEIO ioErr =
>         -- Foreign.C.Error maps EIO to HardwareFault
> ```

Additionally say / forward-link to which function it is that we expect to return `EIO` / raise `HardwareFault`.
It's `ptrace()`, right?

Even better to put it into the suggested `Note` comment I mentioned above, and then just backlink to that here, in `peekErrorHandler`, and so on.
___
*[src/System/Hatrace.hs, line 3711 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMOCg6AtS17ISYK4xw:-MCMOCg6AtS17ISYK4xx:b5r7edg) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L3711)):*
> ```Haskell
>           formatDetailedSyscallExit details
>             (\syscall ->
>                unknownExit syscallArgs $ "raw_syscall(" ++ namedSyscall syscall ++ ")")
> ```

Can we print the registers?

(Even better would be to print the named field pointers, just without the peeked details, but that's probably too much for this PR).

Also, shouldn't we tell the user explicitly why they see this (like `... syscall accessed unpeekable data`)?
___
*[src/System/Hatrace.hs, line 3720 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMOdaV9oBSJmgW7efI:-MCMOdaV9oBSJmgW7efJ:bqsvipq) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L3720)):*
> ```Haskell
>      DetailedSyscallExit
>   -> (Syscall -> IO (FormattedSyscall, ReturnOrErrno))
>   -> (Syscall -> IO (FormattedSyscall, ReturnOrErrno))
> ```

Please haddock the 2 a bit

**Review by nh2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nh2/hatrace/76#-:-MCM_9t_9jeaWDKkYFrL:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @qrilka)

**Review by qrilka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nh2/hatrace/76)* status: all files reviewed, 5 unresolved discussions (waiting on @nh2 and @qrilka)

___
*[example-programs/bad-read-pointer.c, line 26 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMLn_d5jAz25vEtVhi:-MCcwLO80LMKGWh9qBQi:bw1gsuy) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/example-programs/bad-read-pointer.c#L26)):*
<details><summary><i>Previously, nh2 (Niklas Hambüchen) wrote…</i></summary><blockquote>

Should we also check the `errno` here? Would it be `EFAULT` in this case?
</blockquote></details>

For some reason in `bad-open-pointer.c` I get EFAULT but also EINVAL sometimes. I didn't find why that could happen, do you have any ideas?
___
*[src/System/Hatrace.hs, line 2145 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMMJ_g5LwUrtINt0Nn:-MCbOfkk-2jRHXWUfORV:b-896fix) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L2145)):*
<details><summary><i>Previously, nh2 (Niklas Hambüchen) wrote…</i></summary><blockquote>

Additionally say / forward-link to which function it is that we expect to return `EIO` / raise `HardwareFault`.
It's `ptrace()`, right?

Even better to put it into the suggested `Note` comment I mentioned above, and then just backlink to that here, in `peekErrorHandler`, and so on.
</blockquote></details>

Done.
___
*[src/System/Hatrace.hs, line 3711 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMOCg6AtS17ISYK4xw:-MCbP-rt0trqUzZcYzC8:b-4n984e) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L3711)):*
<details><summary><i>Previously, nh2 (Niklas Hambüchen) wrote…</i></summary><blockquote>

Can we print the registers?

(Even better would be to print the named field pointers, just without the peeked details, but that's probably too much for this PR).

Also, shouldn't we tell the user explicitly why they see this (like `... syscall accessed unpeekable data`)?
</blockquote></details>

`syscallArgs` contains registers, they get printed, as for adding words about unpeekable data - I checked the code and it appears that formatting was a bit incorrect, the new fixed version gives e.g.
```
[14068] Entering syscall: KnownSyscall Syscall_open, details: raw syscall with unpeekable args(open)(1, 140724238640712, 4458032, 0, 2, 140724238640696)
[14068] Exited syscall: KnownSyscall Syscall_open, details: raw syscall with unpeekable args(open)(1, 140724238640712, 4458032, 0, 2, 140724238640696) = -1 (Invalid argument)
```
what do you think?

**Review by nh2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nh2/hatrace/76)* status: all files reviewed, 3 unresolved discussions (waiting on @qrilka)

___
*[example-programs/bad-read-pointer.c, line 26 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMLn_d5jAz25vEtVhi:-MCkd3GH3Z2_LyuXyTnr:bvyuhla) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/example-programs/bad-read-pointer.c#L26)):*
<details><summary><i>Previously, qrilka (Kirill Zaborsky) wrote…</i></summary><blockquote>

For some reason in `bad-open-pointer.c` I get EFAULT but also EINVAL sometimes. I didn't find why that could happen, do you have any ideas?
</blockquote></details>

Hmm not sure.

Relevant definitions:

* https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/fs/read_write.c#L542
* https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/fs/read_write.c#L418
* https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/fs/read_write.c#L418
* https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/fs/read_write.c#L406

Especially of the latter 2, there are some `EINVAL` default cases, but I'm not sure which one might be triggering for you.

I'm also not sure why address `42` might every be accessible (haven't checked if it is) -- I would imagine that the first page-sized virtual memory block starting 0 is never mapped, so that `*NULL` always segfaults (but again I haven't checked that).
___
*[src/System/Hatrace.hs, line 3711 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMOCg6AtS17ISYK4xw:-MCk_dt_47KSX6-awZD_:b-83sjoh) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L3711)):*
<details><summary><i>Previously, qrilka (Kirill Zaborsky) wrote…</i></summary><blockquote>

`syscallArgs` contains registers, they get printed, as for adding words about unpeekable data - I checked the code and it appears that formatting was a bit incorrect, the new fixed version gives e.g.
```
[14068] Entering syscall: KnownSyscall Syscall_open, details: raw syscall with unpeekable args(open)(1, 140724238640712, 4458032, 0, 2, 140724238640696)
[14068] Exited syscall: KnownSyscall Syscall_open, details: raw syscall with unpeekable args(open)(1, 140724238640712, 4458032, 0, 2, 140724238640696) = -1 (Invalid argument)
```
what do you think?
</blockquote></details>

Nice!

**Review by qrilka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nh2/hatrace/76)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @nh2)

___
*[example-programs/bad-read-pointer.c, line 26 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMLn_d5jAz25vEtVhi:-MCsNtoe4ZOTlmClfbR-:bng9ftw) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/example-programs/bad-read-pointer.c#L26)):*
<details><summary><i>Previously, nh2 (Niklas Hambüchen) wrote…</i></summary><blockquote>

Hmm not sure.

Relevant definitions:

* https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/fs/read_write.c#L542
* https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/fs/read_write.c#L418
* https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/fs/read_write.c#L418
* https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/fs/read_write.c#L406

Especially of the latter 2, there are some `EINVAL` default cases, but I'm not sure which one might be triggering for you.

I'm also not sure why address `42` might every be accessible (haven't checked if it is) -- I would imagine that the first page-sized virtual memory block starting 0 is never mapped, so that `*NULL` always segfaults (but again I haven't checked that).
</blockquote></details>

actually I see this in an example for `open`, not `read`
___
*[src/System/Hatrace.hs, line 2113 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMM4177LkA7GTQfmbg:-MCsO2Ed8Qt7-jdjlw_K:b-896fix) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L2113)):*
<details><summary><i>Previously, nh2 (Niklas Hambüchen) wrote…</i></summary><blockquote>

Probably needs a haddock on why we have this.
Same for `RawEnter/ExitDetails` below.

Probably best would be to add a comment section like in GHC's note system:

```
-- Note: [Unpeekable syscalls]
--
-- We cannot obtain/print syscall details in all cases, for example when a bad pointer
-- is given to read()/write(). Instead, we just want to print/return ...
-- We implment this by ... *Raw, ... catching EIO ("HardwareFault") ...
```

and then you can put `-- See note [Unpeekable syscalls]` on the various places relevant to it.
</blockquote></details>

Done.
___
*[src/System/Hatrace.hs, line 3720 at r1](https://reviewable.io/reviews/nh2/hatrace/76#-MCMOdaV9oBSJmgW7efI:-MCsOdZ_9EORo5Sdj9he:b-896fix) ([raw file](https://github.com/nh2/hatrace/blob/2964b7672f0cf74d22d71dc7f9f7f76aa83308c8/src/System/Hatrace.hs#L3720)):*
<details><summary><i>Previously, nh2 (Niklas Hambüchen) wrote…</i></summary><blockquote>

Please haddock the 2 a bit
</blockquote></details>

Done.

**Pull request merged**
